docker run -it -d \
  --label traefik.http.routers.kalidushi.rule=Host\(\`kalidushifinancial.loan-pocket.com\`\) \
  --label traefik.http.routers.kalidushi.tls.certresolver=lets-encrypt \
  --label traefik.http.routers.kalidushi.tls=true \
  --label traefik.http.routers.kalidushi.service=kalidushi-credit-http \
  --label traefik.http.services.kalidushi-credit-http.loadbalancer.server.port=80 \
  --name kalidushi \
  --network web \
  --restart always \
  --expose 80 \
 mikoposoft/loan-pocket:version2



