docker run -it -d \
  --label traefik.http.routers.santiamamicrofinance.rule=Host\(\`santiamamicrofinance.phamasoft.com\`\) \
  --label traefik.http.routers.santiamamicrofinance.tls.certresolver=lets-encrypt \
  --label traefik.http.routers.santiamamicrofinance.tls=true \
  --label traefik.http.routers.santiamamicrofinance.service=santiamamicrofinance-credit-http \
  --label traefik.http.services.santiamamicrofinance-credit-http.loadbalancer.server.port=80 \
  --name santiamamicrofinance \
  --network web \
  --restart always \
  --expose 80 \
 emasanga/mikoposoft:may13 



